services:
  backend:
    build: ./tictactoe
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    build: ./react-tic_tac_toe
    ports:
      - "5173:80"
    depends_on:
      - backend